name: Generate PDFs

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "main"

      - name: Generate PDFs
        uses: opf/md-to-pdf-upload-action@v1
        with:
          config: ".github/md-to-pdf/md-to-pdf.config.yml"
          stylings: ".github/md-to-pdf/styling/"
          nextcloud-user: ${{ secrets.NEXTCLOUD_USERNAME }}
          nextcloud-app-access-key: ${{ secrets.NEXTCLOUD_APP_ACCESS_KEY }}
          nextcloud-upload-path: ${{ secrets.NEXTCLOUD_UPLOAD_PATH }}
