name: Generate PDFs

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "main"

      - name: Generate PDFs
        uses: as-op/md-to-pdf-action@v0.0.1
        with:
          config: ".github/md-to-pdf/md-to-pdf.config.yml"
          stylings: ".github/md-to-pdf/styling/"
          nexcloud-user:  ${{ secrets.NEXTCLOUD_USERNAME }}
          nexcloud-app-access-key: ${{ secrets.NEXTCLOUD_APP_ACCESS_KEY }}
          nexcloud-upload-path: ${{ secrets.NEXTCLOUD_UPLOAD_PATHx }}
